[project]
authors = [
    {name = "Gregory Danielson", email = "gregory.danielson3@gmail.com"},
]

[project.urls]
homepage = ""
name = "pdm-name-example"

[build-system]
requires = ["pdm-pep517"]
build-backend = "pdm.pep517.api"

[tool]
[tool.pdm]
