[project]
name = "depextra-b"
version = "1.0.0:"
description = "example project"
authors = []
dependencies = [
    "requests[socks]~=2.25",
]
dev-dependencies = []
requires-python = ">=3.7"
dynamic = []
license = {}

[build-system]
requires = ["pdm-pep517"]
build-backend = "pdm.pep517.api"
